# This sample YAML config file is catered towards running the H264 Encoder Node on a Raspberry Pi based system

# The name of the topic to which the H264 encoder node should subscribe to obtain the feed desired to be encoded
# The topic must be a sensor_msgs/Image message
subscription_topic: "/deepracer/kvs_stream"

# The name of the topic to which H264 encoder node should publish the encoded video stream
# The topic will be a kinesis_video_msgs/KinesisVideoFrame message
publication_topic: "/b9/kvs/video/encoded"

# The size of the subscribed and publishing message queues (default: 100)
# queue_size: 100

# The desired output width of the encoded video stream (default: width of the input image stream)
# output_width:

# The desired output height of the encoded video stream (default: height of the input image stream)
# output_height:

# The numerator when expressing the frame rate as a rational number
fps_numerator: 15

# The denominator when expressing the frame rate as a rational number (default: 1)
fps_denominator: 1

# The target bit rate in bits per second of the output video stream
bitrate: 2048000
